#ifndef INCLUDES
#define INCLUDES
#include <iostream>
#include <string>
#include <vector>
#include <locale>
#include <codecvt>
#include <sstream>
#include <iomanip>
#include <fstream>
#include <random>
#include <numeric>
#include <algorithm>
#include <utility>
#include <set>
#include <functional>
#include "pdfgen.h"
#include "constants.hpp"
#include "function_definicions.hpp"
#include "genders.hpp"
#include "sdl_includes.h"
#include "types.hpp"
#include "topbar_init.hpp"
#include "global_vars.hpp"
#include "general_functions.hpp"
#include "SDL_Addons.hpp"
#include "events.hpp"
#include "tinyfiledialogs.hpp"
#include "gui_normal.hpp"
#include "goofyahh_gui.hpp"
#include "goofyahh_gui_2.hpp"
#include "goofyahh_gui_3.hpp"
#include "gui.hpp"
#include "export.hpp"
#include "grid.hpp"
#include "generation.hpp"
#include "mwm/mwmatching.hpp"
#include "search_alg.hpp"
#include "json.hpp"
#include "csv.hpp"
#include "file_managment.hpp"
#endif