#define ELEMENT_DROPMENU 0
#define ELEMENT_BUTTON 1
#define ELEMENT_NUMBERINPUTBOX 2
#define ELEMENT_TEXTBOX 3
#define ELEMENT_LABEL 4
#define ELEMENT_CHECKBOX 5
#define ELEMENT_SLIDER 6
#define KMOD_COMMAND KMOD_GUI
#define STANDARTPICEHEIGHT 30
#define STANDARTBORDER 2
// #define RETINA_DISPLAY
#define SPLASHSCREENTIME 30
#define CURSORPERIOD 500
#define HOVER_DARKEN 0.6
#define TOPPICEHEIGHT 70
#define BORDERLINEFATNESS 1
#define MAX_STUDENT_PARAMS 20
//colors
#define COLOR_FOREGROUND 0,0,0
#define COLOR_BACKGROUND 180,180,180
#define COLOR_HOVER 150,150,150
#define COLOR_CLICKED 120,120,120
#define COLOR_SELECTED 70,80,240
#define COLOR_SELECTED_HOVER 30,60,150

#define BIG_PANEL_WIDTH 600
#define BIG_PANEL_HEIGHT 400
#define BIG_PANEL_X 50
#define BIG_PANEL_Y 100
#define SMALL_PANEL_WIDTH 300
#define SMALL_PANEL_HEIGHT 200
#define MIN_GRID_SIZE 30
#define MAX_GRID_SIZE 500
#define ZOOM_SPEED 4
#define RENDER_INTERVAL 100

#define TEXT_ASPECT_RATIO 0.8f
