static const std::vector<std::string> genders = {
    "Muž",
    "Žena",
    "Kroasant",
    "Agender",
    "Alzák",
    "Amd Radeon",
    "Amd Ryzen",
    "Androgyne",
    "Angry Face",
    "Aol",
    "Aporagender",
    "Apple Silicon",
    "Ati Radeon",
    "Ati Rage",
    "Atom",
    "Auragender",
    "Bing",
    "Bucket",
    "Blueberry",
    "Bread",
    "C",
    "Čaroděj",
    "Černá díra",
    "Červí díra",
    "Cake",
    "Comet",
    "Cool Face",
    "Copilot",
    "C++",
    "Demiboy",
    "Demigirl",
    "Dimensional Rift",
    "Discord",
    "Duckduckgo",
    "Echo",
    "Eclipse",
    "Edge",
    "Emacs",
    "Error",
    "Everywhere",
    "Facebook",
    "Ferofluid",
    "Foggy",
    "Forestgender",
    "Front",
    "Galaxygender",
    "Genderfluid",
    "Genderqueer",
    "Github",
    "Gitlab",
    "Glitch",
    "Glitter",
    "Google",
    "Google Chrome",
    "Grape",
    "Harmonygender",
    "Horizongender",
    "Humidity",
    "Hvězda",
    "Ice Cream",
    "Ide",
    "Inside",
    "Insider",
    "Instagram",
    "Intel Core",
    "Java",
    "Javascript",
    "Jednorožec",
    "Laughing Face",
    "Left",
    "Lightning",
    "Linkedin",
    "Lunagender",
    "Maverique",
    "Medium",
    "Microsoft Edge",
    "Midnight",
    "Mimozemšťan",
    "Mirrorgender",
    "Moonglow",
    "Moonlight",
    "Moonstone",
    "Motýl",
    "Mozilla Firefox",
    "Mrak",
    "Multivesmír",
    "Mysticgender",
    "Měsíc",
    "Nebulagender",
    "Neongender",
    "Nerd Face",
    "Neynámý",
    "Nightgender",
    "Nonbinary",
    "Notepad",
    "Nowhere",
    "Nutella",
    "Nvidia",
    "Oceangender",
    "Opera",
    "Otayník",
    "Outher",
    "Outsider",
    "Pancake",
    "Pangender",
    "Paradox",
    "Petalgender",
    "Pineapple",
    "Pizza",
    "Polygender",
    "Portál",
    "Programming Language",
    "Pulse",
    "Python",
    "Quantum",
    "Questioning",
    "Radioizotopový termojaderný reaktor",
    "Rain",
    "Rainbow",
    "Rainbowgender",
    "Raspberry",
    "Raspberry Pi",
    "Reddit",
    "Reveriegender",
    "Right",
    "Robot",
    "Sad Face",
    "Safari",
    "Scared Face",
    "Serenegender",
    "Seznam",
    "Simulace",
    "Singularity",
    "Sluníčko",
    "Smallgender",
    "Smiley Face",
    "Snapchat",
    "Snow",
    "Solargender",
    "Sparkgender",
    "Squeweeze",
    "Squeweezegender",
    "Srdce",
    "Stackoverflow",
    "Stardust",
    "Starlight",
    "Stellafem",
    "Stellagender",
    "Stellamasc",
    "Stormy",
    "Strawberry",
    "Stroj času",
    "Sublime Text",
    "Sunbeam",
    "Sunglasses Angry Face",
    "Sunglasses Confused Face",
    "Sunglasses Cool Face",
    "Sunglasses Crying Face",
    "Sunglasses Face",
    "Sunglasses Laughing Face",
    "Sunglasses Nerd Face",
    "Sunglasses Sad Face",
    "Sunglasses Scared Face",
    "Sunglasses Smiley Face",
    "Sunglasses Sunglasses Angry Face",
    "Sunglasses Sunglasses Confused Face",
    "Sunglasses Sunglasses Cool Face",
    "Sunglasses Sunglasses Crying Face",
    "Sunglasses Sunglasses Face",
    "Sunglasses Sunglasses Laughing Face",
    "Sunglasses Sunglasses Nerd Face",
    "Sunglasses Sunglasses Sad Face",
    "Sunglasses Sunglasses Scared Face",
    "Sunglasses Sunglasses Smiley Face",
    "Sunglasses Sunglasses Sunglasses Angry Face",
    "Sunglasses Sunglasses Sunglasses Confused Face",
    "Sunglasses Sunglasses Sunglasses Cool Face",
    "Sunglasses Sunglasses Sunglasses Crying Face",
    "Sunglasses Sunglasses Sunglasses Face",
    "Sunglasses Sunglasses Sunglasses Laughing Face",
    "Sunglasses Sunglasses Sunglasses Nerd Face",
    "Sunglasses Sunglasses Sunglasses Sad Face",
    "Sunglasses Sunglasses Sunglasses Scared Face",
    "Sunglasses Sunglasses Sunglasses Smiley Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Angry Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Confused Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Cool Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Cool Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Crying Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Laughing Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Nerd Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Nerd Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sad Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Scared Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Scared Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Smiley Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Angry Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Confused Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Laughing Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sad Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Smiley Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Crying Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sad Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Smiley Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Angry Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Crying Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Laughing Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Nerd Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Smiley Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Winking Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Sunglasses Winking Face",
    "Sunglasses Sunglasses Sunglasses Sunglasses Winking Face",
    "Sunglasses Sunglasses Sunglasses Winking Face",
    "Sunglasses Sunglasses Winking Face",
    "Sunglasses Winking Face",
    "Symfonie",
    "Šmoula",
    "Šmoulinka",
    "Tea",
    "Teleportér",
    "Text Editor",
    "Thunder",
    "Tiktok",
    "Tor Browser",
    "Traktor",
    "Twitter",
    "Two Spirit",
    "Unicorn Cake",
    "Uni",
    "Vim",
    "Vivaldi",
    "Void",
    "Vs Code",
    "Vzkřičník",
    "Vír",
    "Watermelon",
    "Wikipedia",
    "Wildflower",
    "Wind",
    "Winking Face",
    "X",
    "Xenogender",
    "Yahoo",
    "Yandex",
    "Youtube",
    "Zajíc",
    "Útočná helikoptéra"
};
